### PR TITLE
[synse server] create cluster permissions for plugin discovery

### LINKED ISSUE #5: [synse-server] Needs to create a clusterrolebinding for plugin descovery
On a fresh deploy of synse-server, logs will fail with tracebacks due to Forbidden errors from API

```
[2018-11-01 08:52:32 +0000] - (synse)[DEBUG] scan:31: Re-registering plugins
[2018-11-01 08:52:32 +0000] - (synse)[INFO] plugin:325: No plugin configurations for unix
[2018-11-01 08:52:32 +0000] - (synse)[DEBUG] plugin:327: unix plugin configuration: []
[2018-11-01 08:52:32 +0000] - (synse)[DEBUG] plugin:355: Registering plugins from default socket directory (/tmp/synse/procs)
[2018-11-01 08:52:32 +0000] - (synse)[INFO] plugin:380: Registered unix plugins: []
[2018-11-01 08:52:32 +0000] - (synse)[INFO] plugin:291: No plugin configurations for TCP
[2018-11-01 08:52:32 +0000] - (synse)[DEBUG] kubernetes:34: Using namespace "default" for k8s discovery
[2018-11-01 08:52:32 +0000] - (synse)[DEBUG] kubernetes:86: Using endpoint label selector: component=plugin
[2018-11-01 08:52:32 +0000] - (root)[ERROR] handlers:105: Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 603, in handle_request
response = await response
File "/usr/local/lib/python3.6/site-packages/synse/routes/core.py", line 55, in scan_route
response = await commands.scan(rack=rack, board=board, force=force)
File "/usr/local/lib/python3.6/site-packages/synse/commands/scan.py", line 32, in scan
plugin.register_plugins()
File "/usr/local/lib/python3.6/site-packages/synse/plugin.py", line 199, in register_plugins
addresses = kubernetes.discover()
File "/usr/local/lib/python3.6/site-packages/synse/discovery/kubernetes.py", line 43, in discover
addresses.extend(_register_from_endpoints(ns=ns, cfg=endpoints_cfg))
File "/usr/local/lib/python3.6/site-packages/synse/discovery/kubernetes.py", line 93, in _register_from_endpoints
endpoints = v1.list_namespaced_endpoints(namespace=ns, label_selector=label_selector)
File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11782, in list_namespaced_endpoints
(data) = self.list_namespaced_endpoints_with_http_info(namespace, **kwargs)
File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11885, in list_namespaced_endpoints_with_http_info
collection_formats=collection_formats)
File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
_return_http_data_only, collection_formats, _preload_content, _request_timeout)
File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
_request_timeout=_request_timeout)
File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
headers=headers)
File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
query_params=query_params)
File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 01 Nov 2018 08:52:32 GMT', 'Content-Length': '266'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints is forbidden: User \"system:serviceaccount:default:default\" cannot list endpoints in the namespace \"default\"","reason":"Forbidden","details":{"kind":"endpoints"},"code":403}
```

Since synse-server now uses Kubernetes API for plugin discovery, the chart will need to both create a service-account and a clusterrolebinding for read level permissions. Normally, a `Role` and `RoleBinding` would be sufficient, but since synse-server can technically be configured to search for endpoints not in their namespace, we'll use a `ClusterRole` and `ClusterRoleBinding`

I've not tested these templates, but it would look something like

## serviceaccount.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "labels" . | indent 4 }}
  name: {{ template "fullname" . }}
```

## clusterrole.yaml

Since the URL being accessed is `/api/v1/namespaces/{namespace}/endpoints` we can decompose that into `apiGroups` "core", in one or more namespaces, for the endpoints resource. The method being invoked is `list` so we need at least the `list` and `get` verbs. I've added watch, because it's easy enough to include.

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fullname" . }}
rules:
- apiGroups: [""]                 # Empty string means the Core API group
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
```

## clusterrolebinding.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
{{ include "annotations" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
```

## deployment.yaml
Finally, the `Deployment` template spec will need to be updated to attach the ServiceAccount to synse-server.

Under `spec.template.spec` in the deployment add

```
serviceAccountName: {{ template "fullname" . }}
```

We should do our best to use `fullname` for these item to avoid collisions when multiple releases deployed in a single cluster / namespace.

### PR DESCRIPTION
**Pull request by edaniszewski**
fixes #5 

Tested this on Austin running only Synse Server and some plugins. Without these changes, I saw the permissions failure. With these changes, plugin discovery completed successfully and there were no errors in the logs.

### CODE REVIEW

**Comment by edaniszewski** [comment]
One thing I was thinking about for this was adding a conditional check around the ServiceAccount, ClusterRole, and ClusterRoleBinding to see if kubernetes plugin discovery was enabled. That way, if it is not enabled, we don't create these resources that we don't need, e.g. 

```yaml
# serviceaccount.yaml
{{ if .Values.config.plugin.discover.kubernetes }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
{{ end }}
```

If that sounds like a good idea to others, I could either add it to this PR, or submit those changes in a follow-up PR.

**Comment by marcoceppi** [comment]
I actually think that's a great addition, it'll make these charts more robust for different configurations.

**Comment by MatthewHink** [comment]
What should I do to test this on the VEM? synse/synse-server is version 0.1.0. The version in this branch is 0.1.1. I think that means that if I try to deploy now it will deploy the old chart version, but I could be wrong.

Do I just run this to update the charts? helm package --dependency-update --save .

```
vapor@basx-vec1:~/src/synse-charts/synse-server$ git checkout synse-server-permissions
Branch 'synse-server-permissions' set up to track remote branch 'synse-server-permissions' from 'origin'.
Switched to a new branch 'synse-server-permissions'
vapor@basx-vec1:~/src/synse-charts/synse-server$ git log -n 1
commit ac6bbbeac76bfaeb03c21be384d7e42885d9a287 (HEAD -> synse-server-permissions, origin/synse-server-permissions)
Author: Erick Daniszewski <edaniszewski@gmail.com>
Date:   Thu Nov 1 10:36:03 2018 -0400

    [synse-server] add conditional to render permissions resources only when k8s discovery is configured
vapor@basx-vec1:~/src/synse-charts/synse-server$ helm search | grep synse
local/synse                          	0.0.9        	                            	An HTTP API for the monitoring and control of physical an...
synse/emulator                       	0.1.0        	2.2.0                       	Emulator plugin for Synse Server.
synse/modbus                         	0.1.0        	                            	Synse Modbus Over IP Plugin.
synse/snmp                           	0.1.0        	                            	snmp
synse/synse                          	0.0.9        	                            	An HTTP API for the monitoring and control of physical an...
synse/synse-server                   	0.1.0        	2.2.4                       	An HTTP API for the monitoring and control of physical an...
vapor@basx-vec1:~/src/synse-charts/synse-server$ ls
Chart.yaml  templates  values.yaml
vapor@basx-vec1:~/src/synse-charts/synse-server$ grep version Chart.yaml
version: 0.1.1```

**Comment by marcoceppi** [comment]
This is a great question. What you'll need to do is something like this. I'm going to assume you have two projects checked out:

```
deployment
synse-charts
```

So, change into the `deployment/sites/austin/vapor-hq` and run

```
helm dependency update
helm dependency list
```

You should see `synse-server 0.1.0` in the list output. We're going to delete that

```
rm -f charts/synse-server-0.1.0.tgz
```

This removes the dependency, lets move back to the `synse-charts` directory. In the root, you'll want to checkout this branch and build the new synse-server chart. We're going to put the newly built chart straight into that sites chart directory

```
git checkout -b synse-server-permissions -t origin/synse-server-permissions
helm package -u -d ../deployment/site/austin/vapor-hq/charts synse-server
```

This should result in something like this:

```
Successfully packaged chart and saved it to: ../deployment/site/austin/vapor-hq/charts/synse-server-0.1.1.tgz
```

Now, change back to the `deployment/site/austin/vapor-hq` directory and run the helm install - but omit the `--dep-up` flag. Helm will blindly trust what is in the cache and proceed to use the new synse server.

```
helm install --debug .
```

Verify you've got the new chart by looking for the following service accounts in the debug output:

```
==> v1/ServiceAccount
adj-noun-synse-server  2s

==> v1/ClusterRole
adj-noun-synse-server  2s

==> v1/ClusterRoleBinding
adj-noun-synse-server  2s
```

This can be repeated for any chart in the synse-charts repo for any of the sites. This documentation will find its way in the next few days in the `deployment` README but this should tide you over until then.

**Comment by MatthewHink** [comment]
So this is still bombing. My best guess is that either the synse name resolution is broken in k8 or the synse version route has changes.

``ConnectionError: HTTPConnectionPool(host='synse', port=5000): Max retries exceeded with url: /synse/version (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7feacdbd2350>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-11-01 16:10:27,023 - __init__:438 - Unexpected exception in auto_update poll.
Traceback (most recent call last):
  File "/auto_fan/auto_fan/__init__.py", line 431, in auto_update
    current_loop_data = poll_fan_sensors()
  File "/auto_fan/auto_fan/__init__.py", line 308, in poll_fan_sensors
    current_serial_data.poll()
  File "/auto_fan/auto_fan/control_loop/serial_data.py", line 45, in poll
    self.fan_speed, self.fan_speed_percent, self.fan_direction = self._get_fan_speed_and_direction()
  File "/auto_fan/auto_fan/control_loop/serial_data.py", line 84, in _get_fan_speed_and_direction
    fan_url = self.local_synse_info.get_vapor_fan_url()
  File "/auto_fan/auto_fan/control_loop/data_structures/synse_info.py", line 177, in get_vapor_fan_url
    return self._vapor_fan_url()
  File "/auto_fan/auto_fan/control_loop/data_structures/synse_info.py", line 383, in _vapor_fan_url
    device = self._find_device_by_type_and_info('fan', the_type)
  File "/auto_fan/auto_fan/control_loop/data_structures/synse_info.py", line 701, in _find_device_by_type_and_info
    scan_results = self.get_scan()
  File "/auto_fan/auto_fan/control_loop/data_structures/synse_info.py", line 160, in get_scan
    return self._scan()
  File "/auto_fan/auto_fan/control_loop/data_structures/synse_info.py", line 340, in _scan
    r = requests.get(self.get_prefix() + "scan?force=true",
  File "/auto_fan/auto_fan/control_loop/data_structures/synse_info.py", line 149, in get_prefix
    return self._get_prefix()
  File "/auto_fan/auto_fan/control_loop/data_structures/synse_info.py", line 326, in _get_prefix
    version = self.get_version()
  File "/auto_fan/auto_fan/control_loop/data_structures/synse_info.py", line 140, in get_version
    return self._get_version()
  File "/auto_fan/auto_fan/control_loop/data_structures/synse_info.py", line 309, in _get_version
    r = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='synse', port=5000): Max retries exceeded with url: /synse/version (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7feacdbd2350>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-11-01 16:10:27,023 - health_status:23 - Creating Health results. fan_mode auto, deck deque([False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], maxlen=100), cache_size 6
2018-11-01 16:10:27,024 - health_status:47 - deck_fragment: [False, False, False, False, False, False]
2018-11-01 16:10:27,024 - health_status:49 - self.cache_pass: 0.0
2018-11-01 16:10:27,024 - health_status:53 - self.last_100_pass: 0.0
2018-11-01 16:10:27,024 - health_status:67 - persisting health results to auto_fan_health.json
2018-11-01 16:10:27,025 - __init__:443 - Releasing job lock.
2018-11-01 16:10:27,025 - __init__:446 - auto_update end
vapor@basx-vec1:~/src/synse-charts$ curl http://${SYNSE_IP}:5000/synse/version
{
  "version":"2.2.4",
  "api_version":"v2"
}
vapor@basx-vec1:~/src/synse-charts$ curl http://${FAN_IP}:4997/vaporcore/1.0/fan
{
  "http_code": 500,
  "message": "HTTPConnectionPool(host='synse', port=5000): Max retries exceeded with url: /synse/version (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7feacf6e1a90>: Failed to establish a new connection: [Errno -2] Name or service not known',))"```

**Comment by MatthewHink** [comment]
Above stack is from auto_fan trying to poll synse.

Is this change up on any other site?

**Pull request merged**
